export const history = [
    {
        "olympiadId": 101,
        "olympiadName": "Городская олимпиада по математике",
        "date": "2024-03-15",
        "subject": "Математика",
        "points": 95,
        "maxPoints": 100,
        "status": "Победитель (1 место)",
        "teacher": "Смирнова Е.В.",
        "award": "Золотая медаль",
        "level": "Городской",
    },
    {
        "olympiadId": 205,
        "olympiadName": "Областная олимпиада по физике",
        "date": "2024-02-10",
        "subject": "Физика",
        "points": 80,
        "maxPoints": 100,
        "status": "Призер (3 место)",
        "teacher": "Петров А.Н.",
        "award": "Серебряная медаль",
        "level": "Областной",
    },
    {
        "olympiadId": 178,
        "olympiadName": "Школьная олимпиада по информатике",
        "date": "2023-12-05",
        "subject": "Информатика",
        "points": 65,
        "maxPoints": 100,
        "status": "Участник",
        "teacher": "Козлов Д.С.",
        "award": "Сертификат",
        "level": "Школьный",
    },
    {
        "olympiadId": 302,
        "olympiadName": "Всероссийская олимпиада по математике",
        "date": "2023-11-20",
        "subject": "Математика",
        "points": 72,
        "maxPoints": 100,
        "status": "Участник",
        "teacher": "Смирнова Е.В.",
        "award": null,
        "level": "Всероссийский",
    }
]